version: "3.9"

services:
  backend:
    build: .
    container_name: node-backend
    ports:
      - "4000:7000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: